name: ProtectiveSnowman
version: 1.0.0.1
author: Celeo
website: http://www.darktidegames.com/ 
descriptions: Snowballs do damage to mobs
main: com.darktidegames.celeo.snowman.ProtectiveSnowman
commands:
  protectivesnowman:
    usage: /<command> reload
    descriptions: Reloads from the configuration file