name: ProtectiveSnowman
version: 1.0.1.0
author: Celeo
website: http://www.darktidegames.com/ 
descriptions: Snowballs do damage to mobs
main: com.darktidegames.celeo.snowman.ProtectiveSnowman
commands:
  snowman:
    usage: /<command> [reload|info]
    descriptions: Reloads or shows info on the current settings